### ISSUE TITLE
[BUG] File component arguments not working

### ISSUE THREAD

**Issue by danny-lloyd** [gethinode/hinode#1073]
## Describe the bug

Arguments for the File component are not being respected when used. For example, setting `full` to `false` should make the File component just show the filename and not the whole path but it doesn't work. It looks like it doesn't work on the Hinode docs website or if you create a project from scratch.

## To reproduce

1. Go to https://gethinode.com/docs/components/file/
2. Scroll down to Collapsed file preview or File preview with filename only
3. See neither arguments have worked, file preview is not collapsed and second one shows full path

## Expected behavior

- Path should not be shown with `full="false"`
- Preview should be collapsed with `show="false"`

## Screenshots

<img width="932" alt="Screenshot 2024-08-09 at 13 03 35" src="https://github.com/user-attachments/assets/5ab43d08-19ff-4487-aa78-cdc7b4832e33">

## Host environment

Please complete the following information where applicable.

 - Hinode version: v0.25.1
 - Host OS: macOS Sonoma 14.6.1
 - Node version: v22.5.1
 - Browser: Firefox 129.0 / Safari 17.6

## Hugo environment

Copy the output of `hugo env` or `npm run env` here.

```bash
❯ hugo env
hugo v0.130.0+extended darwin/arm64 BuildDate=2024-07-29T13:51:56Z VendorInfo=brew
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.22.5"
OptionParser::InvalidOption: invalid option: --embedded
  Use --trace for backtrace.
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.3.2"
```

**Comment by d-oit** [comment]
Had the same problem. If you look into the code the vars are bool instead of strings like described in the documentation

show=false
full=false

**Comment by markdumay** [comment]
Thanks for spotting this, I've isolated the issue. There are actually two issues:
- The `file` shortcode should invoke the partial `utilities/CastBool.html` for both `show` and `full` to support both `bool` and `string` arguments (the latter is casted to a bool)
- The `file` shortcode should test if either argument is set, because `with .Get "show"` evaluates to false and will not initialize the argument

The following code shows the proper initialization:

```markdown
{{- $show := true -}}
{{ if isset .Params "show" }}{{ $show = partial "utilities/CastBool.html" (.Get "show") }}{{ end -}}
{{- $full := true -}}
{{ if isset .Params "full" }}{{ $full = partial "utilities/CastBool.html" (.Get "full") }}{{ end -}}
```

I'm preparing a fix that addresses all Hinode shortcodes that support a bool argument.
